{
 "title": "Postgres_exporter",
 "description": "Dashbord works with postgres_exporter for prometheus",
 "tags": [ "postgres" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(pg_stat_activity_count, server)"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "label_values(node_disk_reads_completed{instance=\"$host\", device!~\"dm-.+\"}, device)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(pg_stat_activity_count, instance)"
   },
   { "name": "datname", "label": "Database", "query": "label_values(datname)" },
   {
    "name": "mode",
    "label": "Lock table",
    "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
   },
   {
    "name": "server",
    "label": "Server",
    "query": "query_result(pg_postmaster_start_time_seconds{server!=\"\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Longest Transaction",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration{datname=\"$datname\"}",
     "legendFormat": "max_tx_duration [{{state}}]"
    }
   ]
  },
  {
   "title": "Current fetch data",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\"})"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_inserted{datname=~\"$datname\"})"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\"})"
    }
   ]
  },
  {
   "title": "Number of rows (INSERT/UPDATE/DELETE) by queries in this database",
   "type": "graph",
   "description": "Number of rows inserted by queries in this database, Number of rows updated by queries in this database, Number of rows deleted by queries in this database",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Rows" }
   ],
   "targets": [
    {
     "expr": "topk(1, sum(increase(pg_stat_database_tup_inserted{server=~\"$server\", datname=~\"$datname\"}[2m])) by (server,datname))",
     "legendFormat": "{{server}} ({{datname}}) INSERT"
    },
    {
     "expr": "topk(1, sum(increase(pg_stat_database_tup_updated{server=~\"$server\", datname=~\"$datname\"}[2m])) by (server,datname))",
     "legendFormat": "{{server}} ({{datname}}) UPDATE"
    },
    {
     "expr": "topk(1, sum(increase(pg_stat_database_tup_deleted{server=~\"$server\", datname=~\"$datname\"}[2m])) by (server,datname))",
     "legendFormat": "{{server}} ({{datname}}) DELETE"
    }
   ]
  },
  {
   "title": "Change Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Rows" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_inserted{datname=\"$datname\"}[2m]) ",
     "legendFormat": "INSERT"
    },
    {
     "expr": "irate(pg_stat_database_tup_updated{datname=\"$datname\"}[2m])",
     "legendFormat": "UPDATE"
    },
    {
     "expr": "irate(pg_stat_database_tup_deleted{datname=\"$datname\"}[2m])",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": " Top 10 number of rows affected by the query",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Rows" }
   ],
   "targets": [
    {
     "expr": "topk (10, irate(pg_stat_statements_rows{server=\"prodpgaggr.itdep.org:25433\"}[5m]))",
     "legendFormat": "query id {{query}}"
    }
   ]
  },
  {
   "title": " Number of rows retrieved by request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Rows" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_fetched{datname=~\"$datname\"}[2m])",
     "legendFormat": "{{datname}} SELECT (index scan)"
    },
    {
     "expr": "irate(pg_stat_database_tup_returned{datname=~\"$datname\"}[2m])",
     "legendFormat": "{{datname}}  SELECT (table scan)"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "description": "Number of transactions in this database that have been committed",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(pg_stat_database_xact_commit{datname=~\"$datname\"}[2m])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "delta(pg_stat_database_xact_rollback{datname=~\"$datname\"}[2m])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend{}[2m])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc{}[2m])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync{}[2m])",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{}[2m])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean{}[2m])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Fetch data (SELECT)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\"} != 0",
     "legendFormat": "{{instance}}, {{datname}}"
    }
   ]
  },
  {
   "title": "Insert data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\"} != 0",
     "legendFormat": "{{instance}}, {{datname}}"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{datname=~\"$datname\"} != 0",
     "legendFormat": "{{instance}}, {{datname}}"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\"} ",
     "legendFormat": "{{instance}},{{datname}},state : {{state}}"
    }
   ]
  },
  {
   "title": "Idle sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"} !=0",
     "legendFormat": "{{instance}},{{datname}},state : {{state}}"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_locks_count{datname=~\"$datname\", mode=~\"$mode\"} != 0",
     "legendFormat": "{{instance}},{{datname}},{{mode}}"
    }
   ]
  },
  {
   "title": "Delete data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_deleted{datname=~\"$datname\"} != 0",
     "legendFormat": "{{instance}}, {{datname}}"
    }
   ]
  },
  {
   "title": "Return data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_returned{datname=~\"$datname\"} != 0",
     "legendFormat": "{{instance}}, {{datname}}"
    }
   ]
  },
  {
   "title": "Top Transaction Rollbacks",
   "type": "graph",
   "description": "Number of transactions in this database that have been rolled back",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(2, sum(increase(pg_stat_database_xact_rollback{server=~\"$server\", datname=~\"$datname\"}[2m])) by (server,datname))",
     "legendFormat": "{{server}} ({{datname}})"
    }
   ]
  },
  {
   "title": "Total query time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "ms", "label": "Rows" }
   ],
   "targets": [
    {
     "expr": "topk (30, rate(pg_stat_statements_total_time{server=~\"$server\"}[2m]))",
     "legendFormat": "{{query}}"
    }
   ]
  }
 ]
}