{
 "title": "Requests, limits and usage",
 "description": "Nearly all default values exported by Prometheus node exporter graphed.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_container_info,namespace)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "CPU Cores Requested in $namespace",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "CPU Cores Limited in $namespace",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "CPU Cores Usage in $namespace",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"^$namespace$\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory Requested in $namespace",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Memory Limited in $namespace",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Memory Usage in $namespace",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"^$namespace$\"})"
    }
   ]
  },
  {
   "title": "CPU Containers usage/request in $namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (container,pod)(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",container!=\"POD\"}[5m])) / sum by (container,pod)(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"})",
     "legendFormat": "{{ container }} IN_POD {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage/request in $namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (container,pod)(container_memory_working_set_bytes{namespace=~\"$namespace\",container!=\"\",container!=\"POD\"}) / sum by (container,pod)(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\"})",
     "legendFormat": "{{ container }} IN_POD {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage/limit in $namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (container,pod)(container_memory_working_set_bytes{namespace=~\"$namespace\",container!=\"\",container!=\"POD\"}) / sum by (container,pod)(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\"})",
     "legendFormat": "{{ container }} IN_POD {{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Containers Request in $namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container,pod)(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"})",
     "legendFormat": "{{ container }} IN_POD {{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Containers Limit in $namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container,pod)(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\"})",
     "legendFormat": "{{ container }} IN_POD {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Containers Request in $namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (container,pod)(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\"})",
     "legendFormat": "{{ container }} IN_POD {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Containers Limit in $namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (container,pod)(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\"})",
     "legendFormat": "{{ container }} IN_POD {{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Containers Usage in $namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container,pod)(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",container!=\"POD\"}[5m]))",
     "legendFormat": "{{ container }} IN_POD {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage in $namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (container,pod)(container_memory_working_set_bytes{namespace=~\"$namespace\",container!=\"\",container!=\"POD\"})",
     "legendFormat": "{{ container }} IN_POD {{ pod }}"
    }
   ]
  }
 ]
}