{
 "title": "Used | Wasted Resources",
 "description": "Dashboard to show the resource requests vs allocatable in the cluster",
 "tags": [
  "kubernetes",
  "k8s",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_labels, namespace)"
   },
   {
    "name": "app",
    "label": "app",
    "query": "label_values(kube_pod_labels{namespace=\"$namespace\"}, label_app)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(kube_node_info, node)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Wide", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "kbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable{resource=\"memory\"} / 1024 ) by (instance))",
     "legendFormat": "Allocatable Memory"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{resource=\"memory\"} / 1024 ) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)\n )",
     "legendFormat": "Requested Memory"
    },
    {
     "expr": "min(sum(kube_node_status_capacity_memory_bytes / 1024 ) by (instance))",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum(kube_metrics_server_pods_mem)",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 5, "x": 7, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{resource=\"memory\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)\n ) / min(sum(kube_node_status_allocatable{resource=\"memory\"}) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Allocatable Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 1 },
   "format": "kbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_metrics_server_pods_mem)"
    }
   ]
  },
  {
   "title": "Wasted CPU %",
   "type": "bargauge",
   "gridPos": { "h": 30, "w": 2, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "((100 * \n(sum(label_replace(sum(kube_metrics_server_pods_cpu) / 1000000000 , \"pod\", \"$1\", \"pod_name\", \"(.*)\")))\n/ \nsum(\nsum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)\n )\n- 100) * -1)"
    }
   ]
  },
  {
   "title": "Wasted Ram %",
   "type": "bargauge",
   "gridPos": { "h": 30, "w": 2, "x": 22, "y": 1 },
   "targets": [
    {
     "expr": "((100 * \n(sum(label_replace(sum(kube_metrics_server_pods_mem) * 1024 , \"pod\", \"$1\", \"pod_name\", \"(.*)\")))\n/\nsum(\nsum(kube_pod_container_resource_requests{unit=\"byte\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)\n )\n- 100) * -1)"
    }
   ]
  },
  {
   "title": "Requested Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{resource=\"memory\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)\n )"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_cpu_cores) by (instance))",
     "legendFormat": "Allocatable CPU Cores"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)\n )",
     "legendFormat": "Requested CPU Cores"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 5, "x": 7, "y": 11 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{resource=\"memory\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)\n ) / min(sum(kube_node_status_allocatable{resource=\"memory\"}) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Allocatable CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Used CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_metrics_server_pods_cpu) / 1000000000"
    }
   ]
  },
  {
   "title": "Requested CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)\n )"
    }
   ]
  },
  {
   "title": "Wasted Memory by Namespace %",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "((100 * (sum(label_replace(sum(kube_metrics_server_pods_mem) by (pod_namespace), \"namespace\", \"$1\", \"pod_namespace\", \"(.*)\")) by (namespace) * 1024)/ sum(sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (namespace, pod)* on (namespace, pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (namespace, pod) == 1)) by (namespace)- 100) * -1) > 0",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Requests/Limit/Usage by Namespace",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{namespace=~\".*\", resource=\"memory\"}) by (namespace, pod)\n * on (namespace, pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=~\".*\"}) by (namespace, pod) == 1)\n ) by (namespace)",
     "legendFormat": "Requested Memory"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_limits{namespace=~\".*\", resource=\"memory\"}) by (namespace, pod)\n * on (namespace, pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=~\".*\"}) by (namespace, pod) == 1)\n ) by (namespace)",
     "legendFormat": "Limit Memory"
    },
    {
     "expr": "label_replace(sum(kube_metrics_server_pods_mem) by (pod_namespace), \"namespace\", \"$1\", \"pod_namespace\", \"(.*)\")",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "(sum(sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (namespace, pod)* on (namespace, pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (namespace, pod) == 1)) by (namespace))\n-\n(sum(label_replace(sum(kube_metrics_server_pods_mem) by (pod_namespace), \"namespace\", \"$1\", \"pod_namespace\", \"(.*)\")) by (namespace) * 1024)",
     "legendFormat": "Wasted Memory"
    },
    {
     "expr": "((100 * \n(sum(label_replace(sum(kube_metrics_server_pods_mem) by (pod_namespace), \"namespace\", \"$1\", \"pod_namespace\", \"(.*)\")) by (namespace) * 1024)\n/ \nsum(sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (namespace, pod)* on (namespace, pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (namespace, pod) == 1)) by (namespace)\n- 100) * -1)",
     "legendFormat": "Wasted Memory %"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{namespace=~\".*\", resource=\"cpu\"}) by (namespace, pod)\n * on (namespace, pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=~\".*\"}) by (namespace, pod) == 1)\n ) by (namespace)",
     "legendFormat": "Requested CPU"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_limits{namespace=~\".*\", resource=\"cpu\"}) by (namespace, pod)\n * on (namespace, pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (namespace, pod) == 1)\n ) by (namespace)",
     "legendFormat": "Limit CPU"
    },
    {
     "expr": "label_replace(sum(kube_metrics_server_pods_cpu) by (pod_namespace) / 1000000000 , \"namespace\", \"$1\", \"pod_namespace\", \"(.*)\")",
     "legendFormat": "Used CPU"
    },
    {
     "expr": "(sum(sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (namespace, pod)* on (namespace, pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (namespace, pod) == 1)) by (namespace))\n-\n(sum(label_replace(sum(kube_metrics_server_pods_cpu) by (pod_namespace) / 1000000000 , \"namespace\", \"$1\", \"pod_namespace\", \"(.*)\")) by (namespace))",
     "legendFormat": "Wasted CPU"
    },
    {
     "expr": "((100 * \n(sum(label_replace(sum(kube_metrics_server_pods_cpu) by (pod_namespace) / 1000000000 , \"namespace\", \"$1\", \"pod_namespace\", \"(.*)\")) by (namespace))\n/ \nsum(sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (namespace, pod)* on (namespace, pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (namespace, pod) == 1)) by (namespace)\n- 100) * -1)",
     "legendFormat": "Wasted CPU %"
    }
   ]
  },
  { "title": "Resource by Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "kbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$namespace\"}) by (pod) == 1)\n ) / 1000",
     "legendFormat": "Requested Memory"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$namespace\"}) by (pod) == 1)\n ) / 1000",
     "legendFormat": "Limit Memory"
    },
    {
     "expr": "sum(kube_metrics_server_pods_mem{pod_namespace=\"$namespace\"})",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "Allocatable Memory",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 40 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$namespace\"}) by (pod) == 1)\n )"
    }
   ]
  },
  {
   "title": "Limit Memory",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 40 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$namespace\"}) by (pod) == 1)\n )"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 40 },
   "format": "kbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_metrics_server_pods_mem{pod_namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_metrics_server_pods_cpu{pod_namespace=\"$namespace\"}) / 1000000000",
     "legendFormat": "Used CPU"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$namespace\"}) by (pod) == 1)\n )",
     "legendFormat": "Requested CPU"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$namespace\"}) by (pod) == 1)\n )",
     "legendFormat": "Limit CPU"
    }
   ]
  },
  {
   "title": "Allocatable CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$namespace\"}) by (pod) == 1)\n )"
    }
   ]
  },
  {
   "title": "Limit CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$namespace\"}) by (pod) == 1)\n )"
    }
   ]
  },
  {
   "title": "Used CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_metrics_server_pods_cpu{pod_namespace=\"$namespace\"}) / 1000000000"
    }
   ]
  },
  {
   "title": "Memory Request/Limit by Pod",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"})  by (pod)"
    },
    {
     "expr": "label_replace(sum(kube_metrics_server_pods_mem{pod_namespace=~\"$namespace\"}) by (pod_name), \"pod\", \"$1\", \"pod_name\", \"(.*)\")"
    },
    {
     "expr": "((100 * \n(sum(label_replace(sum(kube_metrics_server_pods_mem{pod_namespace=~\"$namespace\"}) by (pod_name), \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) * 1024)\n/ \nsum(sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$namespace\"}) by (pod)* on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)) by (pod)\n- 100) * -1)",
     "legendFormat": "Wasted Live %"
    }
   ]
  },
  {
   "title": "CPU Request/Limit by Pod",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"$namespace\"}) by (pod)* on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=~\"$namespace\"}) by (pod)* on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)"
    },
    {
     "expr": "label_replace(sum(kube_metrics_server_pods_cpu{pod_namespace=~\"$namespace\"}) by (pod_name) / 1000000000 , \"pod\", \"$1\", \"pod_name\", \"(.*)\") "
    },
    {
     "expr": "((100 * \n(sum(label_replace(sum(kube_metrics_server_pods_cpu{pod_namespace=~\"$namespace\"}) by (pod_name), \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / 1000000000)\n/ \nsum(sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"$namespace\"}) by (pod)* on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)) by (pod)\n- 100) * -1)",
     "legendFormat": "Wasted CPU %"
    }
   ]
  },
  { "title": "Resource by app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Memory by app",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "kbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",pod=~\"($app)-[0-9a-fA-F].*\"})/ 1024",
     "legendFormat": "Requested Memory $app"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=~\"$app.*\"}) / 1024",
     "legendFormat": "Limit Memory $app"
    },
    {
     "expr": "sum(kube_metrics_server_pods_mem{pod_namespace=\"$namespace\", pod_name=~\"$app.*\"})",
     "legendFormat": "Used Memory $app"
    }
   ]
  },
  {
   "title": "CPU Cores by app",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\",pod=~\"($app)-[0-9a-fA-F].*\"})",
     "legendFormat": "Requested CPU $app"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\",pod=~\"($app)-[0-9a-fA-F].*\"})",
     "legendFormat": "Limit CPU $app"
    },
    {
     "expr": "sum(kube_metrics_server_pods_cpu{pod_namespace=\"$namespace\", pod_name=~\"($app)-[0-9a-fA-F].*\"}) / 1000000000",
     "legendFormat": "Used CPU $app"
    }
   ]
  },
  {
   "title": "Memory by pod",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "kbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",pod=~\"($app)-[0-9a-fA-F].*\"}) by (pod) / 1024",
     "legendFormat": "Requested Memory {{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=~\"($app)-[0-9a-fA-F].*\"})  by (pod) / 1024",
     "legendFormat": "Limit Memory {{pod}}"
    },
    {
     "expr": "sum(kube_metrics_server_pods_mem{pod_namespace=\"$namespace\", pod_name=~\"($app)-[0-9a-fA-F].*\"})  by (pod_name)",
     "legendFormat": "Used Memory {{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Cores by pod",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\",pod=~\"($app)-[0-9a-fA-F].*\"}) by (pod)",
     "legendFormat": "Requested CPU {{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\",pod=~\"($app)-[0-9a-fA-F].*\"}) by (pod)",
     "legendFormat": "Limit CPU {{pod}}"
    },
    {
     "expr": "sum(kube_metrics_server_pods_cpu{pod_namespace=\"$namespace\", pod_name=~\"($app)-[0-9a-fA-F].*\"}) by (pod_name) / 1000000000",
     "legendFormat": "Used CPU {{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Request/Limit by Pod",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",pod=~\"($app)-[0-9a-fA-F].*\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\",pod=~\"($app)-[0-9a-fA-F].*\"})  by (pod)"
    },
    {
     "expr": "label_replace(sum(kube_metrics_server_pods_mem{pod_namespace=~\"$namespace\",pod_name=~\"($app)-[0-9a-fA-F].*\"}) by (pod_name), \"pod\", \"$1\", \"pod_name\", \"(.*)\")"
    },
    {
     "expr": "label_replace(sum(avg_over_time(kube_metrics_server_pods_mem{pod_namespace=~\"$namespace\",pod_name=~\"($app)-[0-9a-fA-F].*\"}[1d])) by (pod_name), \"pod\", \"$1\", \"pod_name\", \"(.*)\")"
    },
    {
     "expr": "label_replace(sum(avg_over_time(kube_metrics_server_pods_mem{pod_namespace=~\"$namespace\",pod_name=~\"($app)-[0-9a-fA-F].*\"}[2d])) by (pod_name), \"pod\", \"$1\", \"pod_name\", \"(.*)\")"
    },
    {
     "expr": "label_replace(sum(max_over_time(kube_metrics_server_pods_mem{pod_namespace=~\"$namespace\",pod_name=~\"($app)-[0-9a-fA-F].*\"}[2d])) by (pod_name), \"pod\", \"$1\", \"pod_name\", \"(.*)\")"
    }
   ]
  },
  {
   "title": "CPU Request/Limit by Pod",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\",pod=~\"($app)-[0-9a-fA-F].*\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\",pod=~\"($app)-[0-9a-fA-F].*\"}) by (pod)"
    },
    {
     "expr": "label_replace(sum(kube_metrics_server_pods_cpu{pod_namespace=~\"$namespace\",pod_name=~\"($app)-[0-9a-fA-F].*\"}) by (pod_name) / 1000000000 , \"pod\", \"$1\", \"pod_name\", \"(.*)\") "
    },
    {
     "expr": "label_replace(sum(avg_over_time(kube_metrics_server_pods_cpu{pod_namespace=~\"$namespace\",pod_name=~\"($app)-[0-9a-fA-F].*\"}[1d])) by (pod_name) / 1000000000, \"pod\", \"$1\", \"pod_name\", \"(.*)\")"
    },
    {
     "expr": "label_replace(sum(avg_over_time(kube_metrics_server_pods_cpu{pod_namespace=~\"$namespace\",pod_name=~\"($app)-[0-9a-fA-F].*\"}[2d])) by (pod_name) / 1000000000, \"pod\", \"$1\", \"pod_name\", \"(.*)\")"
    },
    {
     "expr": "label_replace(sum(max_over_time(kube_metrics_server_pods_cpu{pod_namespace=~\"$namespace\",pod_name=~\"($app)-[0-9a-fA-F].*\"}[2d])) by (pod_name) / 1000000000, \"pod\", \"$1\", \"pod_name\", \"(.*)\")"
    }
   ]
  },
  { "title": "Resource by Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Nodes Allocatable vs Usage",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"}) by (node)"
    },
    {
     "expr": "label_replace(sum(kube_metrics_server_nodes_mem) by (exported_instance), \"node\", \"$1\", \"exported_instance\", \"(.*)\") "
    }
   ]
  },
  {
   "title": "CPU Allocatable vs Usage",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"}) by (node)"
    },
    {
     "expr": "label_replace(sum(kube_metrics_server_nodes_cpu) by (exported_instance) / 1000000000 , \"node\", \"$1\", \"exported_instance\", \"(.*)\") "
    }
   ]
  },
  {
   "title": "CPU / Memory Allocatable vs Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "decbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", node=~\"$instance\"}) by (node)",
     "legendFormat": "Memory Allocatable: {{node}}"
    },
    {
     "expr": "sum(kube_metrics_server_nodes_mem{exported_instance=~\"$instance\"}) by (exported_instance) * 1024",
     "legendFormat": "Memory Utilization: {{exported_instance}}"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", node=~\"$instance\"}) by (node)",
     "legendFormat": "CPU Allocatable: {{node}}"
    },
    {
     "expr": "sum(kube_metrics_server_nodes_cpu{exported_instance=~\"$instance\"}) by (exported_instance) / 1000000000 ",
     "legendFormat": "CPU Utilization: {{exported_instance}}"
    }
   ]
  }
 ]
}